[build]
publish = "exampleSite/public"
command = "cd exampleSite && hugo --minify --themesDir=../../ --theme=repo -b=https://hbs.razonyang.com/"

[build.environment]
NODE_VERSION = "17.6.0"

[context.production.environment]
HUGO_VERSION = "0.93.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
GO_VERSION = "1.17.7"

[context.develop]
command = "cd exampleSite && node --version && npm install && hugo --minify --themesDir=../../ --theme=repo -b=https://develop.hbs.razonyang.com/"

[context.develop.environment]
HUGO_VERSION = "0.93.0"
HUGO_ENABLEGITINFO = "true"
GO_VERSION = "1.17.7"

[context.deploy-preview.build]
command = "cd exampleSite && hugo --minify --themesDir=../../ --theme=repo -b=$DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.93.0"
HUGO_ENABLEGITINFO = "true"
GO_VERSION = "1.17.7"

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "deny"
    X-XSS-Protection = "1; mode=block"

[[redirects]]
  from = "/:lang/*"
  to = "/:lang/404.html"
  status = 404
