name = "Cypherpunks Brasil"
license = "MIT"
licenselink = "https://creativecommons.org/publicdomain/zero/1.0/deed.pt_BR"
description = "Cypherpunks Brasil é um projeto dedicado a tradução de textos históricos e compartilhamento de conteúdo relacionado a criptoanarquismo, cypherpunk, criptologia e mais."
homepage = "https://cypherpunks.com.br/"
tags = [
  "cypherpunks",
  "cypherpunk",
  "criptoanarquia",
  "criptoanarquismo",
  "criptografia",
  "segurança",
  "anarquismo",
  "agorismo",
  "cryptography",
  "cypherpunks brasil"
]
features = [
  "blog",
  "informações",
  "comments"
]
min_version = "0.75.0"
[author]
  name = "Cypherpunks Brasil"
  homepage = "https://github.com/cypherpunksbr"
