[[main]]
  identifier = "dropdown"
  name = "下拉菜单"
  pre = '<i class="fas fa-fw fa-chevron-circle-down"></i>'
[[main]]
  id = "github"
  parent = "dropdown"
  name = "Github"
  url = "https://github.com/razonyang/hugo-theme-bootstrap"
  pre = '<i class="fab fa-fw fa-github"></i>'
[[main]]
  id = "search"
  parent = "dropdown"
  name = "搜索"
  url = "search"
  pre = '<i class="fas fa-fw fa-search"></i>'
