[[main]]
  name = "主页"
  url = "/zh/"
  weight = 10
[[main]]
  name = "分类"
  url = "/zh/categories/"
  weight = 20
[[main]]
  name = "标签"
  url = "/zh/tags/"
  weight = 30
[[main]]
  name = "归档"
  url = "/zh/archives/"
  weight = 40
[[main]]
  name = "关于"
  url = "/zh/about/"
  weight = 50
[[main]]
  name = "下拉菜单"
  identifier = "dropdown"
[[main]]
  parent = "dropdown"
  name = "菜单"
  weight = 10
  url = "#"
[[main]]
  parent = "dropdown"
  name = "另一菜单"
  weight = 20
  url = "#"
[[main]]
  parent = "dropdown"
  name = "外部链接"
  weight = 90
  url = "https://github.com/razonyang/hugo-theme-bootstrap"
