mainSections = ["post", "posts"]

author = "Razon Yang"
titleSeparator = "-"

dateFormat = "Jan 2, 2006"

# Google Analytics
googleAnalytics = ""

# Site verification
googleSiteVerification = ""
bingSiteVerification = ""

[utterances]
repo = "razonyang/hugo-theme-bootstrap"
#issueTerm = "pathname" # pathname, url, title, og:title
#label = "comment"
#theme = "github-light" # github-light, github-dark, preferred-color-scheme, github-dark-orange, icy-dark, dark-blue, photon-dark.

[[social]]
key = "github"
user = "username"
[[social]]
key = "gitlab"
user = "username"
[[social]]
key = "twitter"
user = "username"
[[social]]
key = "facebook"
user = "username"
[[social]]
key = "linkedin"
user = "username"
[[social]]
key = "stackoverflow"
user = "userid"
[[social]]
key = "weibo"
user = "username"
[[social]]
key = "zhihu"
user = "username"
[[social]]
key = "email"
user = "user@example.com"
