email = "user@domain.tld"
facebook = "facebookusername"
github = "githubusername"
gitlab = "gitlabusername"
linkedin = "linkedinusername"
stackoverflow = "stackoverflowuserid"
twitter = "twitterusername"
weibo = "weibousername"
zhihu = "zhihuusername"
instagram = "instagramusername"
quora = "quorausername"
tumblr = "tumblrusername"
reddit = "redditusername"
telegram = "telegramusername"
qq = "qqnumber"
dockerhub = "dockerhubusername"
bitbucket = "bitbucketworkspaceid"
medium = "yourmediumusername" # Medium username or custom domain(e.g. https://yourname.medium.com).
lastfm = "yourlastfmusername"
